# ========================================
# Streamlit server settings
# ========================================
[server]
headless = true           # コンテナ／App Service では true 固定
port     = "$PORT"        # ★環境変数 PORT（App Service が注入）に丸投げ
enableCORS            = false  # 逆プロキシの背後なら無効化しても可
enableXsrfProtection  = true   # CORS を切るならこちらは true に
# address = "0.0.0.0"          # 明示的にバインドしたい場合のみ

# （オプション）Cookie 署名キー。Key Vault から環境変数で渡すならコメントアウト
# cookieSecret = "<<<long-random-hex>>>"

# ========================================
# UI theme
# ========================================
[theme]
primaryColor            = "#3b82f6"
backgroundColor         = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor               = "#e2e8f0"
font                    = "sans serif"   # 有効値: sans serif / serif / monospace



